spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  
  # Oracle Database Configuration
  datasource:
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: system
      password: password
      driver-class-name: oracle.jdbc.OracleDriver
    
    # PostgreSQL Database Configuration
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.dbcomparator: DEBUG